name: home-assistant-client
version: 0.1.0.0
github: "mbg/home-assistant-client"
license: BSD-3-Clause
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"
copyright: "2025 Michael B. Gale"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis: Client library for the Home Assistant API.
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mbg/home-assistant-client#readme>

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingVia
  - FlexibleInstances
  - GADTs
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - TypeOperators

dependencies:
  - aeson >= 2.2.3 && < 2.3
  - base >= 4.7 && < 5
  - bytestring >= 0.12.1 && < 0.13
  - containers >= 0.6.8 && < 0.8
  - deriving-aeson >= 0.2.10 && < 0.3
  - exceptions >= 0.10.9 && < 0.11
  - http-client >= 0.7.19 && < 0.8
  - http-client-tls >= 0.3.6 && < 0.4
  - http-types >= 0.12.4 && < 0.13
  - servant >= 0.20.3 && < 0.21
  - servant-client >= 0.20.3 && < 0.21
  - text >= 2.1.1 && < 2.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  ha-client:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - home-assistant-client
      - optparse-applicative >= 0.18.0 && < 0.20

tests:
  home-assistant-client-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - home-assistant-client
