name: "Release"

on:
  push:
    paths:
      - ".github/workflows/hackage.yml"
  release:
    types:
      - released
      - prereleased

jobs:
  publish-to-hackage:
    name: "Publish to Hackage"
    runs-on: ubuntu-latest

    steps:
      - name: "Dump context"
        shell: bash
        env:
          EVENT_DATA: "${{ toJson(github) }}"
        run: echo $EVENT_DATA | jq

      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: "Check source distribution"
        shell: bash
        run: stack sdist .

      - name: Publish `home-assistant-client`
        if: startsWith(github.ref, 'refs/tags/v') && github.event.action == 'released'
        shell: bash
        run: stack upload . --candidate --no-save-hackage-creds
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_KEY }}
