name: "Release"

on:
  push:
    paths:
      - ".github/workflows/hackage.yml"
  release:
    types:
      - created
      - published
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: "The tag of the release to use for the workflow run."
        required: true
      environment:
        type: string
        description: "The deployment environment. Leave blank for testing."
        default: ""
        required: false

concurrency:
  group: hackage
  cancel-in-progress: false

jobs:
  publish-to-hackage:
    name: "Publish to Hackage"
    runs-on: ubuntu-latest
    environment: ${{ (github.event.action == 'published' && 'Hackage') || inputs.environment || '' }}

    steps:
      - name: "Dump context"
        shell: bash
        env:
          EVENT_DATA: "${{ toJson(github) }}"
        run: echo $EVENT_DATA | jq

      - name: "Clone repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release || github.ref }}

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: "Check source distribution"
        shell: bash
        run: stack sdist .

      - name: Publish `home-assistant-client`
        if: |
          (startsWith(github.ref, 'refs/tags/v') && github.event.action == 'published') ||
          (github.event_name == 'workflow_dispatch' && inputs.environment == 'Hackage')
        shell: bash
        run: stack upload . --candidate --no-save-hackage-creds
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_KEY }}
