name: "Release"

on:
  push:
    paths:
      - ".github/workflows/hackage.yml"
  release:
    types:
      - created
      - published
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: "The tag of the release to use for the workflow run."
        required: true
      environment:
        type: string
        description: "The deployment environment. Leave blank for testing."
        default: ""
        required: false

concurrency:
  group: hackage
  cancel-in-progress: false

jobs:
  build-binaries:
    name: "Build release binaries"
    if: |
      (github.event_name == 'release' &&
      github.event.action != 'published') ||
      github.event_name != 'release'
    uses: ./.github/workflows/haskell.yml

  publish-to-hackage:
    name: "Publish to Hackage"
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event.action == 'published' && 'Hackage') || inputs.environment || '' }}
      url: "https://hackage.haskell.org/package/home-assistant-client-${{ steps.determine-version.outputs.version }}"

    steps:
      - name: "Dump context"
        shell: bash
        env:
          EVENT_DATA: "${{ toJson(github) }}"
        run: echo $EVENT_DATA | jq

      - name: "Clone repository"
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.release || github.ref }}

      - name: "Determine version"
        id: determine-version
        shell: bash
        run: |
          PACKAGE_VERSION="$(yq '.version' package.yaml)"
          echo $PACKAGE_VERSION
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: "Check source distribution"
        shell: bash
        run: stack sdist .

      - name: Publish `home-assistant-client`
        if: |
          (startsWith(github.ref, 'refs/tags/v') && github.event.action == 'published') ||
          (github.event_name == 'workflow_dispatch' && inputs.environment == 'Hackage')
        shell: bash
        run: stack upload . --candidate --no-save-hackage-creds
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_KEY }}
