name: "Haskell"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    inputs:
      attest:
        type: boolean
        default: false

concurrency:
  group: haskell-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Create bin directory"
        shell: bash
        run: mkdir bin

      - name: "Build & Test"
        uses: mbg/actions/stack/build@v0.3
        with:
          upload-docs: ${{ matrix.os == 'ubuntu-24.04-arm' }}
          install-dir: bin

      - name: "Create attestation"
        id: create-attestation
        if: inputs.attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: bin/ha-client

      - name: "Archive ha-client binary"
        shell: bash
        env:
          OS: ${{ runner.os }}
          ARCH: ${{ runner.arch }}
        run: |
          tar -czvf ha-client-$OS-$ARCH.tar.gz bin/ha-client

      - name: "Upload ha-client binary"
        uses: actions/upload-artifact@v4
        with:
          path: ha-client-${{ runner.os }}-${{ runner.arch }}.tar.gz
          name: ha-client-${{ runner.os }}-${{ runner.arch }}
