name: "Haskell"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

concurrency:
  group: haskell-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Create bin directory"
        shell: bash
        run: mkdir bin

      - name: "Build & Test"
        uses: mbg/actions/stack/build@v0.3
        with:
          upload-docs: ${{ matrix.os == 'ubuntu-24.04-arm' }}
          install-dir: bin

      - name: "Upload ha-client binary"
        uses: actions/upload-artifact@v4
        with:
          path: bin/ha-client
          name: ha-client-${{ runner.os }}-${{ runner.arch }}
