name: "Haskell"

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: haskell-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: mbg/actions/stack/build@v0.2
        with:
          upload-docs: ${{ matrix.os == 'ubuntu-24.04-arm' }}
